services:
  hub:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: hub
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - hub_net
      - drogamais_net

networks:
  hub_net:
    driver: bridge
  drogamais_net:
    name: drogamais_net
    driver: bridge